package cn.courselens;
import android.app.*;
import android.os.*;
import android.content.*;
import android.view.*;
import android.widget.*;
import android.graphics.*;
import java.io.*;
import java.lang.reflect.*;

public class NativeChecks extends Instrumentation {
 private boolean scrollOnly;
 @Override public void onCreate(Bundle args){super.onCreate(args);scrollOnly="true".equals(args.getString("scrollOnly"));start();}
 private void main(Runnable work){java.util.concurrent.atomic.AtomicReference<Throwable> failure=new java.util.concurrent.atomic.AtomicReference<>();runOnMainSync(()->{try{work.run();}catch(Throwable e){failure.set(e);}});if(failure.get()!=null)throw new RuntimeException(failure.get());}
 private String encoded(String value){java.util.List<String> rows=new java.util.ArrayList<>();for(Course c:Course.parse(value))rows.add(c.encode());return String.join("\n",rows);}
 private void check(boolean b,String m){if(!b)throw new AssertionError(m);}
 private void set(Object o,String key,Object value)throws Exception{Field f=o.getClass().getDeclaredField(key);f.setAccessible(true);f.set(o,value);}
 private Object get(Object o,String key)throws Exception{Field f=o.getClass().getDeclaredField(key);f.setAccessible(true);return f.get(o);}
 private void call(Object o,String name)throws Exception{Method m=o.getClass().getDeclaredMethod(name);m.setAccessible(true);m.invoke(o);}
 private void form(MainActivity a,Course course,int index)throws Exception{Method m=MainActivity.class.getDeclaredMethod("courseForm",Course.class,int.class,Runnable.class);m.setAccessible(true);m.invoke(a,course,index,(Runnable)()->{try{call(a,"home");}catch(Exception e){throw new RuntimeException(e);}});}
 private void nativeOnly(View v){check(!(v instanceof android.webkit.WebView),"WebView is still present");if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++)nativeOnly(((ViewGroup)v).getChildAt(i));}
 private void render(Activity a,String file)throws Exception{render(a,a.getWindow().getDecorView(),file);}
 private void render(Activity a,View view,String file)throws Exception{android.os.SystemClock.sleep(350);main(()->{try{check(view.getWidth()>0&&view.getHeight()>0,"View not laid out");Bitmap b=Bitmap.createBitmap(view.getWidth(),view.getHeight(),Bitmap.Config.ARGB_8888);view.draw(new Canvas(b));try(FileOutputStream out=a.openFileOutput(file,0)){b.compress(Bitmap.CompressFormat.PNG,100,out);}b.recycle();}catch(Exception e){throw new RuntimeException(e);}});}
 private void schedulePickers(MainActivity activity)throws Exception{
  View decor=activity.getWindow().getDecorView();Object formRoot=get(activity,"root");ViewGroup[] picker=new ViewGroup[1];View[] row=new View[1];Method open=MainActivity.class.getDeclaredMethod("courseChoicePicker",Spinner.class,String.class,String[].class);open.setAccessible(true);
  for(String tag:new String[]{"course-day","course-start","course-end"}){
   Spinner choice=(Spinner)((View)formRoot).findViewWithTag(tag);int initial=choice.getSelectedItemPosition();String[] values=new String[choice.getCount()];for(int i=0;i<values.length;i++)values[i]=(String)choice.getItemAtPosition(i);
   main(()->{try{((EditText)((View)formRoot).findViewWithTag("course-name")).setText("未保存草稿");ViewGroup next=(ViewGroup)open.invoke(activity,choice,choice.getContentDescription().toString(),values);if(picker[0]!=null)check(next==picker[0],"Picker views recreated between fields");picker[0]=next;View nextRow=next.findViewWithTag("choice-option-0");if(row[0]!=null)check(row[0]==nextRow,"Option views recreated");row[0]=nextRow;check(next.getParent()==((View)formRoot).getParent(),"Picker created a separate window");}catch(Exception e){throw new RuntimeException(e);}});waitForIdleSync();render(activity,"qa-"+tag+".png");
   main(()->{try{check(((RadioButton)picker[0].findViewWithTag("choice-option-"+initial)).isChecked(),"Current choice not marked");check(picker[0].findViewWithTag("choice-option-"+(values.length-1)).getVisibility()==View.VISIBLE,"Last choice missing");activity.onBackPressed();check(!(boolean)get(picker[0],"open"),"Back did not close picker");check(get(activity,"root")==formRoot&&choice.getSelectedItemPosition()==initial,"Back changed form");check(((EditText)((View)formRoot).findViewWithTag("course-name")).getText().toString().equals("未保存草稿"),"Draft lost");}catch(Exception e){throw new RuntimeException(e);}});
   for(int selected:new int[]{values.length-1,0}){main(()->{try{check(open.invoke(activity,choice,choice.getContentDescription().toString(),values)==picker[0],"Reopening recreated picker");picker[0].findViewWithTag("choice-option-"+selected).performClick();check(!(boolean)get(picker[0],"open"),"Selection did not dismiss picker");}catch(Exception e){throw new RuntimeException(e);}});waitForIdleSync();check(choice.getSelectedItemPosition()==selected,"Selection failed");}
   main(()->{try{open.invoke(activity,choice,choice.getContentDescription().toString(),values);picker[0].findViewWithTag("choice-cancel").performClick();open.invoke(activity,choice,choice.getContentDescription().toString(),values);}catch(Exception e){throw new RuntimeException(e);}});SystemClock.sleep(300);waitForIdleSync();main(()->{try{check(picker[0].isShown()&&(boolean)get(picker[0],"open"),"Stale closing animation hid reopened picker");check(activity.getWindow().getDecorView()==decor,"Reopening replaced activity window");picker[0].findViewWithTag("choice-shade").performClick();choice.setSelection(initial);}catch(Exception e){throw new RuntimeException(e);}});SystemClock.sleep(200);waitForIdleSync();check(picker[0].getVisibility()==View.INVISIBLE,"Picker did not finish closing");
  }
  main(()->{check(((View)formRoot).getImportantForAccessibility()!=View.IMPORTANT_FOR_ACCESSIBILITY_NO_HIDE_DESCENDANTS,"Form accessibility not restored");});
 }
 private void emptyStates(MainActivity activity)throws Exception{
  for(boolean imported:new boolean[]{false,true}){
   ViewGroup[] grid=new ViewGroup[1];main(()->{try{String original=(String)get(activity,"data");try{set(activity,"data",imported?"1|1|2|测试课程|A101|1":"");Class<?> type=Class.forName("cn.courselens.MainActivity$WeekGrid");Constructor<?> constructor=type.getDeclaredConstructor(MainActivity.class);constructor.setAccessible(true);grid[0]=(ViewGroup)constructor.newInstance(activity);int width=activity.getResources().getDisplayMetrics().widthPixels,height=Math.round(792*activity.getResources().getDisplayMetrics().density);grid[0].layout(0,0,width,height);Method build=MainActivity.class.getDeclaredMethod("buildGrid",type,int.class);build.setAccessible(true);build.invoke(activity,grid[0],2);TextView message=grid[0].findViewWithTag("timetable-empty-message");check(message!=null&&message.getText().toString().equals(imported?"行到水穷处，坐看云起时":"还没有导入课表"),"Wrong empty-state text");ViewGroup empty=(ViewGroup)message.getParent();check(empty.getChildCount()==(imported?1:2),"Empty state still has illustration");TextView link=empty.findViewWithTag("timetable-import");check(imported?link==null:(link!=null&&link.hasOnClickListeners()&&link.getText().toString().contains("登录学校账号")),"Import explanation or action incorrect");grid[0].measure(View.MeasureSpec.makeMeasureSpec(width,View.MeasureSpec.EXACTLY),View.MeasureSpec.makeMeasureSpec(height,View.MeasureSpec.EXACTLY));grid[0].layout(0,0,width,height);int rowHeight=Math.round(66*activity.getResources().getDisplayMetrics().density);check(empty.getTop()==3*rowHeight,"Empty text is not aligned with lesson four");check(message.getHeight()>=rowHeight,"Empty text row collapsed");if(imported)check(message.getLetterSpacing()==.04f&&message.getTextSize()>17*activity.getResources().getDisplayMetrics().scaledDensity,"Poem typography missing");if(imported){build.invoke(activity,grid[0],1);check(grid[0].findViewWithTag("timetable-empty-message")==null,"Empty text shown on a week with courses");build.invoke(activity,grid[0],2);grid[0].measure(View.MeasureSpec.makeMeasureSpec(width,View.MeasureSpec.EXACTLY),View.MeasureSpec.makeMeasureSpec(height,View.MeasureSpec.EXACTLY));grid[0].layout(0,0,width,height);}}finally{set(activity,"data",original);}}catch(Exception e){throw new RuntimeException(e);}});render(activity,grid[0],imported?"qa-empty-week.png":"qa-no-timetable.png");
  }
 }
 private void scrollReturn(MainActivity a)throws Exception{
  main(()->{try{((ScrollView)get(a,"timetableScroll")).scrollTo(0,a.getResources().getDisplayMetrics().densityDpi);}catch(Exception e){throw new RuntimeException(e);}});waitForIdleSync();
  int timetableY=((ScrollView)get(a,"timetableScroll")).getScrollY();check(timetableY>0,"Timetable scroll fixture did not move");int timetableWeek=(int)get(a,"week");

  main(()->{try{Method detail=MainActivity.class.getDeclaredMethod("detail",Course.class);detail.setAccessible(true);detail.invoke(a,Course.parse((String)get(a,"data")).get(0));}catch(Exception e){throw new RuntimeException(e);}});waitForIdleSync();render(a,"qa-detail.png");check(((View)get(a,"root")).getScaleX()==1f&&((View)get(a,"root")).getAlpha()==1f,"Page animation did not settle");main(()->a.onBackPressed());check(!(boolean)get(a,"showingDetail"),"Detail back failed");
  waitForIdleSync();main(()->{try{check(((ScrollView)get(a,"timetableScroll")).getScrollY()==timetableY,"Detail return reset timetable scroll");check((int)get(a,"week")==timetableWeek,"Detail return changed week");call(a,"menu");call(a,"termPicker");}catch(Exception e){throw new RuntimeException(e);}});waitForIdleSync();
  main(()->a.onBackPressed());waitForIdleSync();main(()->a.onBackPressed());waitForIdleSync();main(()->{try{check(((ScrollView)get(a,"timetableScroll")).getScrollY()==timetableY,"Nested settings return reset timetable scroll");}catch(Exception e){throw new RuntimeException(e);}});
 }
 @Override public void onStart(){Bundle result=new Bundle();int resultCode=Activity.RESULT_CANCELED;MainActivity a=null;android.content.SharedPreferences prefs=getTargetContext().getSharedPreferences("MainActivity",0);java.util.Map<String,?> backup=prefs.getAll();try{File stored=new File(getTargetContext().getApplicationInfo().dataDir,"shared_prefs/MainActivity.xml");if(stored.exists())java.nio.file.Files.copy(stored.toPath(),new File(getTargetContext().getFilesDir(),"qa-preferences-backup.xml").toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);
  check(SchoolClient.allowed("https://vpn.squ.edu.cn/enlink/sso/login"),"HTTPS school endpoint rejected");check(!SchoolClient.allowed("http://vpn.squ.edu.cn/login"),"HTTP allowed");check(!SchoolClient.allowed("https://vpn.squ.edu.cn.evil.test/"),"Foreign host allowed");check(!SchoolClient.allowed("https://user@vpn.squ.edu.cn/"),"URL credentials allowed");
  String encrypted=SchoolClient.encrypt("fixture-password-测试","1234567890abcdef");check(encrypted.equals("KpsJYjI3915sfm3+D3a8xvmgWWxyeuU+4aJTryKOpis="),"AES differs from school login algorithm");
  String html="<table><tr><th>节</th><th>星期一</th><th>星期二</th><th>星期三</th><th>星期四</th><th>星期五</th><th>星期六</th><th>星期日</th></tr><tr><td>1</td><td rowspan='2'><div>数据结构<sup>0300311.006</sup></div><div>(1~16单周) (1-2节) 3-204</div><div>英语<sup>0300312.006</sup></div><div>(6周) (1-2节) X116</div></td><td></td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>2</td><td>电路<sup>0300313.006</sup><div>(6周) (2-2节) 3-303</div></td></tr></table>";
  String parsed=SchoolParser.htmlCourses(html);check(parsed.contains("1|1|2|数据结构|3-204|1,3,5,7,9,11,13,15"),"HTML/odd week parsing failed");check(parsed.contains("1|1|2|英语|X116|6"),"Multiple course names failed");check(parsed.contains("2|2|2|电路|3-303|6"),"Rowspan weekday failed");
  check(SchoolParser.jsonCourses("[{\"lessonId\":12,\"dayOfWeek\":2,\"startUnit\":3,\"endUnit\":5,\"weekIndices\":[6,8],\"roomName\":\"3-304\"}]","{\"lessons\":[{\"id\":12,\"course\":{\"nameZh\":\"马克思主义基本原理\"}}]}").equals("2|3|5|马克思主义基本原理|3-304|6,8"),"JSON schedule adapter failed");
  check(SchoolParser.jsonCourses("{\"studentTableVms\":[{\"activities\":[{\"lessonId\":12,\"courseName\":\"大学物理实验\",\"weekday\":6,\"startUnit\":6,\"endUnit\":7,\"weekIndexes\":[6,8],\"room\":\"L403\",\"teachers\":[\"测试教师\"]}]}]}","{\"lessons\":[]}").equals("6|6|7|大学物理实验|L403|6,8|测试教师"),"School print-data schema failed");
  a=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).setAction(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();MainActivity activity=a;check(((String)get(a,"data")).equals(a.getPreferences(0).getString("courses","")),"Saved timetable not restored");
  emptyStates(activity);
  String original=(String)get(a,"data");int oldWeek=(int)get(a,"week");String oldNotes=(String)get(a,"notes");
  main(()->{try{
   set(activity,"data","1|1|2|本周课程|A|6\n1|1|2|本周课程|A|6\n1|1|2|重叠课程|B|6\n2|3|4|其他周课程|C|7\n3|5|6|单周课程|D|1,3,5,7");
   Class<?> type=Class.forName("cn.courselens.MainActivity$WeekGrid");Constructor<?> constructor=type.getDeclaredConstructor(MainActivity.class);constructor.setAccessible(true);ViewGroup grid=(ViewGroup)constructor.newInstance(activity);grid.layout(0,0,700,900);
   Method build=MainActivity.class.getDeclaredMethod("buildGrid",type,int.class);build.setAccessible(true);
   for(int shownWeek:new int[]{6,7,8}){build.invoke(activity,grid,shownWeek);int cards=0;for(int i=0;i<grid.getChildCount();i++){View child=grid.getChildAt(i);if(child.getContentDescription()==null)continue;cards++;String label=child.getContentDescription().toString();check(shownWeek==6?(label.startsWith("本周课程，")||label.startsWith("重叠课程，")):(shownWeek==7&&(label.startsWith("其他周课程，")||label.startsWith("单周课程，"))),"Course from another week rendered");check(child.getAlpha()==1f,"Course card is dimmed");if(shownWeek==6)check(child.getLayoutParams().width>=140,"Duplicate course wasted a collision lane");}check(cards==(shownWeek==8?0:2),"Week filtering or duplicate removal failed");}
   set(activity,"data",original);
  }catch(Exception e){throw new RuntimeException(e);}});
  main(()->{try{InputStream in=getTargetContext().getAssets().open("sample.txt");String sample=new java.util.Scanner(in,"UTF-8").useDelimiter("\\A").next().replace("\uFEFF","");set(activity,"data",sample+"\n1|3|4|多周回归课程|测试教室|1,7,16");set(activity,"week",6);set(activity,"notes","");call(activity,"home");}catch(Exception e){throw new RuntimeException(e);}});waitForIdleSync();main(()->nativeOnly(activity.getWindow().getDecorView()));
  render(a,"qa-before-paging.png");
  if(scrollOnly){scrollReturn(activity);result.putString("result","PASS: detail and nested settings preserve nonzero timetable scroll and selected week; previous empty states preserved");resultCode=Activity.RESULT_OK;return;}
  Object rootBefore=get(a,"root");androidx.viewpager.widget.ViewPager pager=(androidx.viewpager.widget.ViewPager)get(a,"pager");java.util.concurrent.CountDownLatch settled=new java.util.concurrent.CountDownLatch(1);
  main(()->{pager.addOnPageChangeListener(new androidx.viewpager.widget.ViewPager.SimpleOnPageChangeListener(){public void onPageScrollStateChanged(int state){if(state==androidx.viewpager.widget.ViewPager.SCROLL_STATE_IDLE)settled.countDown();}});pager.setCurrentItem(6,true);});
  check(settled.await(4,java.util.concurrent.TimeUnit.SECONDS),"Week paging did not settle");check((int)get(a,"week")==7,"Week header failed");check(rootBefore==get(a,"root"),"Week swipe rebuilt the entire screen");check(a.getPreferences(0).getString("courses","").equals(get(a,"data")),"Timetable not persisted");for(int target:new int[]{7,16,1,6}){
   main(()->pager.setCurrentItem(target-1,false));waitForIdleSync();android.os.SystemClock.sleep(350);
   main(()->{try{ViewGroup visible=null;for(int i=0;i<pager.getChildCount();i++){View child=pager.getChildAt(i);if(child.getLeft()==pager.getScrollX())visible=(ViewGroup)child;}check(visible!=null&&visible.getWidth()>0,"Selected week grid missing");int cards=0;java.util.Set<String> expected=new java.util.HashSet<>();for(Course c:Course.parse((String)get(activity,"data")))if(c.active(target))expected.add(c.day+":"+c.start+":"+c.end+":"+c.name+":"+c.room+":"+c.teacher);for(int i=0;i<visible.getChildCount();i++){View card=visible.getChildAt(i);if(card.getContentDescription()==null)continue;cards++;check(card.getWidth()>0&&card.getLeft()>=0&&card.getRight()<=visible.getWidth(),"Course card outside selected week grid");}check(!expected.isEmpty(),"Paging fixture must contain courses in week "+target);check(cards==expected.size(),"Selected week "+target+" course cards missing");}catch(Exception e){throw new RuntimeException(e);}});
  }
  render(a,"qa-timetable.png");
  scrollReturn(activity);
  String beforeEditing=(String)get(a,"data");
  main(()->{try{call(activity,"edit");}catch(Exception e){throw new RuntimeException(e);}});waitForIdleSync();render(a,"qa-course-manager.png");
  main(()->{try{form(activity,null,-1);}catch(Exception e){throw new RuntimeException(e);}});waitForIdleSync();render(a,"qa-course-form.png");
  schedulePickers(activity);
  main(()->{try{((EditText)((View)get(activity,"root")).findViewWithTag("course-name")).setText("");}catch(Exception e){throw new RuntimeException(e);}});
  main(()->{try{View root=(View)get(activity,"root");nativeOnly(root);for(int mode=0;mode<3;mode++){root.findViewWithTag("course-weeks-"+mode).performClick();for(int w=1;w<=30;w++)check(((ToggleButton)root.findViewWithTag("course-week-"+w)).isChecked()==(mode==0||(mode==1&&w%2==1)||(mode==2&&w%2==0)),"Week shortcut selection failed");}View button=root.findViewWithTag("course-week-30");for(ViewParent parent=button.getParent();parent!=null;parent=parent.getParent())if(parent instanceof ScrollView){((ScrollView)parent).fullScroll(View.FOCUS_DOWN);break;}}catch(Exception e){throw new RuntimeException(e);}});waitForIdleSync();render(a,"qa-course-form-weeks.png");
  main(()->{try{View root=(View)get(activity,"root");root.findViewWithTag("save-course").performClick();check(((EditText)root.findViewWithTag("course-name")).getError()!=null,"Blank name accepted");((EditText)root.findViewWithTag("course-name")).setText("独立添加课程");((Spinner)root.findViewWithTag("course-start")).setSelection(4);((Spinner)root.findViewWithTag("course-end")).setSelection(1);root.findViewWithTag("save-course").performClick();check(((TextView)root.findViewWithTag("course-error")).getText().toString().contains("结束"),"Reversed units accepted");check(beforeEditing.equals(get(activity,"data")),"Invalid form changed courses");activity.onBackPressed();check(beforeEditing.equals(get(activity,"data")),"Cancelled form changed courses");form(activity,null,-1);root=(View)get(activity,"root");((EditText)root.findViewWithTag("course-name")).setText("独立添加课程");((EditText)root.findViewWithTag("course-teacher")).setText("测试老师");((EditText)root.findViewWithTag("course-room")).setText("A101");((Spinner)root.findViewWithTag("course-day")).setSelection(1);((Spinner)root.findViewWithTag("course-start")).setSelection(2);((Spinner)root.findViewWithTag("course-end")).setSelection(3);root.findViewWithTag("course-weeks-3").performClick();root.findViewWithTag("save-course").performClick();check(((TextView)root.findViewWithTag("course-error")).getText().toString().contains("教学周"),"Empty weeks accepted");for(int w:new int[]{1,7,16})((ToggleButton)root.findViewWithTag("course-week-"+w)).setChecked(true);root.findViewWithTag("save-course").performClick();java.util.List<Course> courses=Course.parse((String)get(activity,"data"));check(courses.size()==Course.parse(beforeEditing).size()+1,"Adding course replaced timetable");Course added=courses.get(courses.size()-1);check(added.teacher.equals("测试老师")&&added.room.equals("A101")&&added.day==2&&added.start==3&&added.end==4&&added.weeks.equals("1,7,16"),"Form fields did not round trip");check(((String)get(activity,"data")).startsWith(encoded(beforeEditing)+"\n"),"Unrelated courses changed");form(activity,added,courses.size()-1);root=(View)get(activity,"root");check(((EditText)root.findViewWithTag("course-teacher")).getText().toString().equals("测试老师"),"Teacher not prefilled");((EditText)root.findViewWithTag("course-room")).setText("B202");root.findViewWithTag("save-course").performClick();courses=Course.parse((String)get(activity,"data"));check(courses.size()==Course.parse(beforeEditing).size()+1&&courses.get(courses.size()-1).room.equals("B202"),"Single course edit failed");check(((String)get(activity,"data")).startsWith(encoded(beforeEditing)+"\n"),"Edit changed unrelated courses");check(get(activity,"pageBack")==null,"Form save did not return home");set(activity,"data",beforeEditing);call(activity,"save");call(activity,"weekPicker");}catch(Exception e){throw new RuntimeException(e);}});waitForIdleSync();render(a,"qa-weeks.png");
  main(()->{try{((View)get(activity,"root")).findViewWithTag("week-1").performClick();check((int)get(activity,"week")==1,"Week picker did not select week");check(beforeEditing.equals(get(activity,"data")),"Week selection changed courses");}catch(Exception e){throw new RuntimeException(e);}});main(()->{try{call(activity,"menu");}catch(Exception e){throw new RuntimeException(e);}});waitForIdleSync();render(a,"qa-settings.png");
  main(()->{try{call(activity,"termPicker");}catch(Exception e){throw new RuntimeException(e);}});waitForIdleSync();render(a,"qa-term.png");
  main(()->{try{activity.onBackPressed();Method clear=MainActivity.class.getDeclaredMethod("confirmClear");clear.setAccessible(true);AlertDialog dialog=(AlertDialog)clear.invoke(activity);check(dialog!=null&&dialog.isShowing(),"Clear confirmation missing");dialog.getButton(AlertDialog.BUTTON_NEGATIVE).performClick();check(beforeEditing.equals(get(activity,"data")),"Cancelled clear deleted courses");activity.onBackPressed();}catch(Exception e){throw new RuntimeException(e);}});
  main(()->{try{set(activity,"data",original);set(activity,"week",oldWeek);set(activity,"notes",oldNotes);call(activity,"login");}catch(Exception e){throw new RuntimeException(e);}});waitForIdleSync();main(()->{nativeOnly(activity.getWindow().getDecorView());try{check(!((View)get(activity,"password")).isSaveEnabled(),"Password can enter saved view state");}catch(Exception e){throw new RuntimeException(e);}});render(a,"qa-login.png");
  check(SchoolParser.clean("3-304 普通教室 范晓丽 &nbsp<span style='color: red'>免听</span>").equals("3-304 普通教室 范晓丽 免听"),"HTML leaked into course metadata");check(SchoolClient.passwordRejected("密码错误"),"Wrong password not detected");check(!SchoolClient.passwordRejected("请检查密码或验证码"),"Ambiguous failure clears password");
  SchoolClient client=new SchoolClient();client.prepare();result.putString("school","HTTPS native login form and token loaded; captcha="+client.captchaRequired);
  result.putString("result","PASS: TLS, AES, parsing, week paging, all secondary pages, individual course add/edit/validation, cancelled clear and return navigation; no credentials used");
  resultCode=Activity.RESULT_OK;
 }catch(Throwable e){result.putString("error",e.toString());}finally{android.content.SharedPreferences.Editor editor=prefs.edit().clear();for(java.util.Map.Entry<String,?> entry:backup.entrySet()){Object value=entry.getValue();if(value instanceof String)editor.putString(entry.getKey(),(String)value);else if(value instanceof Integer)editor.putInt(entry.getKey(),(Integer)value);}check(editor.commit(),"Original preferences not restored");finish(resultCode,result);}}
}
